services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database  # your PostgreSQL database name
          property: connectionString
    plan: free
